version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${PORT_DB}:5432
  app:
    image: amaris-back-db-1
    restart: always
    ports:
      - 3002:3002
    depends_on:
      - db
